# .scrutinizer.yml

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage:
        timeout: 600    # Timeout in seconds.
    js_hint: true
    php_sim: true
    php_pdepend: true
    php_analyzer: true

filter:
    paths: [src/*.php]